name: Publish

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "npm"
          registry-url: "https://registry.npmjs.org"
      - run: npm ci
      - run: npm run build --if-present

      - name: publish wormhole-kit-core package
        uses: JS-DevTools/npm-publish@v1
        id: wormhole-kit-core
        with:
            token: ${{ secrets.NPM_TOKEN }}
            package: "./packages/wormhole-kit-core/package.json"

      - name: publish wormhole-kit package
        uses: JS-DevTools/npm-publish@v1
        id: wormhole-kit
        with:
            token: ${{ secrets.NPM_TOKEN }}
            package: "./packages/wormhole-kit/package.json"
    