name: Publish

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: "npm"
          registry-url: "https://registry.npmjs.org"
      - run: npm ci
      - run: npm run build --if-present

      - name: publish wormhole-kit-core package
        uses: JS-DevTools/npm-publish@v3
        id: wormhole-kit-core
        with:
            access: public
            token: ${{ secrets.NPM_TOKEN }}
            package: "packages/wormhole-kit-core/package.json"
            strategy: upgrade

      - name: publish wormhole-kit package
        uses: JS-DevTools/npm-publish@v3
        id: wormhole-kit
        with:
            access: public
            token: ${{ secrets.NPM_TOKEN }}
            package: "packages/wormhole-kit/package.json"
            strategy: upgrade
    